### ISSUE TITLE
Member 엔티티 추가

### ISSUE THREAD

**Issue by topyheun** [topyheun/marketplace#4]

**Comment by hojihun5516** [comment]
```

    @Column(name = "member_username")
    private String username;

    @Column(name = "member_password")
    private String password;
    
```

필드명과 column이름을 굳이 다르게 가져가게 된 이유가 있나요??

memberTable에 member_username이 아닌 다른 username이 들어가게 될 경우가 있나요??

**Comment by topyheun** [comment]
> ```
> 
>     @Column(name = "member_username")
>     private String username;
> 
>     @Column(name = "member_password")
>     private String password;
>     
> ```
> 
> 필드명과 column이름을 굳이 다르게 가져가게 된 이유가 있나요??
> 
> memberTable에 member_username이 아닌 다른 username이 들어가게 될 경우가 있나요??


접두사를 사용하여 컬럼명을 구성하면 해당 컬럼이 어떤 테이블에 속해있는지 명확하게 알 수 있습니다. 
그리고 다른 테이블에서 동일한 이름을 가진 컬럼을 사용하는 경우가 있을때 헷갈리지 않는 장점도 있습니다.
